# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 332)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(170, 270, 84, 19))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(30, 270, 121, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 261, 251))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_PPPoE = QtWidgets.QPushButton(self.tab)
        self.pushButton_PPPoE.setGeometry(QtCore.QRect(20, 10, 211, 31))
        self.pushButton_PPPoE.setStyleSheet("")
        self.pushButton_PPPoE.setObjectName("pushButton_PPPoE")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 41, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_Speedtest = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Speedtest.setGeometry(QtCore.QRect(20, 10, 211, 31))
        self.pushButton_Speedtest.setObjectName("pushButton_Speedtest")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 60, 111, 19))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 90, 101, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 120, 131, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 150, 121, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 180, 121, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_Ping = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Ping.setGeometry(QtCore.QRect(20, 10, 211, 31))
        self.pushButton_Ping.setObjectName("pushButton_Ping")
        self.pushButton_Ping2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Ping2.setGeometry(QtCore.QRect(20, 50, 211, 31))
        self.pushButton_Ping2.setObjectName("pushButton_Ping2")
        self.checkBox_google = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_google.setGeometry(QtCore.QRect(20, 120, 101, 19))
        self.checkBox_google.setChecked(True)
        self.checkBox_google.setObjectName("checkBox_google")
        self.checkBox_ya = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_ya.setGeometry(QtCore.QRect(20, 150, 84, 19))
        self.checkBox_ya.setObjectName("checkBox_ya")
        self.checkBox_vk = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_vk.setGeometry(QtCore.QRect(20, 180, 84, 19))
        self.checkBox_vk.setObjectName("checkBox_vk")
        self.checkBox_github = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_github.setGeometry(QtCore.QRect(140, 90, 111, 19))
        self.checkBox_github.setObjectName("checkBox_github")
        self.checkBox_pornhub = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_pornhub.setGeometry(QtCore.QRect(140, 120, 101, 19))
        self.checkBox_pornhub.setObjectName("checkBox_pornhub")
        self.checkBox_mailnchelny = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_mailnchelny.setGeometry(QtCore.QRect(20, 90, 121, 19))
        self.checkBox_mailnchelny.setChecked(True)
        self.checkBox_mailnchelny.setObjectName("checkBox_mailnchelny")
        self.checkBox_python = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_python.setGeometry(QtCore.QRect(140, 180, 91, 19))
        self.checkBox_python.setObjectName("checkBox_python")
        self.checkBox_googleip = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_googleip.setGeometry(QtCore.QRect(140, 150, 84, 19))
        self.checkBox_googleip.setObjectName("checkBox_googleip")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(290, 10, 801, 291))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PPPoE Shmon"))
        self.checkBox.setText(_translate("MainWindow", "Auto clear"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear list"))
        self.pushButton_PPPoE.setText(_translate("MainWindow", "PPPoE check start"))
        self.label.setText(_translate("MainWindow", "Server lost:"))
        self.label_2.setText(_translate("MainWindow", "Server bad:"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PPPoE"))
        self.pushButton_Speedtest.setText(_translate("MainWindow", "&Speedtest"))
        self.checkBox_2.setText(_translate("MainWindow", "MTS Izhevsk"))
        self.checkBox_3.setText(_translate("MainWindow", "MTS Moscow"))
        self.checkBox_4.setText(_translate("MainWindow", "MTS N.Novgorod"))
        self.checkBox_5.setText(_translate("MainWindow", "DOM.RU Kazan"))
        self.checkBox_6.setText(_translate("MainWindow", "MTS N.Chelny"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Speedtest"))
        self.pushButton_Ping.setText(_translate("MainWindow", "Ping"))
        self.pushButton_Ping2.setText(_translate("MainWindow", "Fast Ping"))
        self.checkBox_google.setText(_translate("MainWindow", "google.com"))
        self.checkBox_ya.setText(_translate("MainWindow", "ya.ru"))
        self.checkBox_vk.setText(_translate("MainWindow", "vk.com"))
        self.checkBox_github.setText(_translate("MainWindow", "github.com"))
        self.checkBox_pornhub.setText(_translate("MainWindow", "pornhub.com"))
        self.checkBox_mailnchelny.setText(_translate("MainWindow", "mail.n-chelny.ru"))
        self.checkBox_python.setText(_translate("MainWindow", "python.org"))
        self.checkBox_googleip.setText(_translate("MainWindow", "8.8.8.8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Ping"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Info"))

